name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Démarrer l’API et vérifier /health
        run: |
          flask --app app run --host=127.0.0.1 --port=8080 &
          sleep 3
          curl --fail http://127.0.0.1:8080/health
